version: "3.6"

services:
  python:
    build:
      context: .
      dockerfile: ./docker/production/Dockerfile
    tty: true
    command: /bin/sh "dagit.sh"
    working_dir: /scrapper
    volumes:
      - ./:/scrapper:Z
    env_file:
      - .env
    depends_on:
      - mongo
    ports:
      - 127.0.0.1:3000:3000
    networks:
      - backend

  mongo:
    image: mongo
    restart: always
    ports:
      - 127.0.0.1:27017:27017
    volumes:
      - ./db/:/data/db:Z
    env_file:
      - .env
    networks:
      - backend

networks:
  backend:
    driver: bridge
